// Generated by CoffeeScript 1.6.3
(function() {
  var doc, errorNotFound, presenceCheck, required_obj, win;
  win = window;
  doc = document;
  required_obj = {};
  errorNotFound = function(required) {
    throw Error('not found ' + required);
  };
  presenceCheck = function(required) {
    var temp, val, _i, _len, _ref;
    temp = win;
    _ref = required.split('.');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      val = _ref[_i];
      temp = temp[val];
      if (!temp) {
        break;
      }
    }
    return temp;
  };
  win['read'] = function(required, srcpath) {
    var cls, xhr;
    cls = presenceCheck(required);
    if (!cls) {
      if (srcpath && !required_obj[srcpath]) {
        required_obj[srcpath] = true;
        xhr = new XMLHttpRequest;
        xhr.onreadystatechange = function() {
          var script;
          if (xhr.readyState === 4) {
            if (xhr.status === 200) {
              doc.head.appendChild(script = doc.createElement('script'));
              script.text = xhr.responseText;
            } else {
              throw Error('file load error: ' + required);
            }
          }
        };
        xhr.open('GET', srcpath + '.js?t=' + (+(new Date)), false);
        xhr.send();
      } else {
        errorNotFound(required);
      }
    }
    if (!(cls = presenceCheck(required))) {
      errorNotFound(required);
    }
    return cls;
  };
})();
