// Generated by CoffeeScript 1.6.3
(function(win, doc, required_obj, reg_readmethod, errorNotFound, time) {
  var checkPersence, getFile, read, srcpathNoCache, xhrSyncScriptLoad;
  srcpathNoCache = function(srcpath) {
    return srcpath + '?t=' + time;
  };
  checkPersence = function(required) {
    var i, temp;
    required = required.split('.');
    temp = win;
    for (i in required) {
      temp = temp[required[i]];
      if (!temp) {
        break;
      }
    }
    return temp;
  };
  getFile = function(srcpath, callback) {
    var res, xhr;
    res = '';
    xhr = new XMLHttpRequest;
    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4) {
        if (xhr.status === 200) {
          res = '\n' + xhr.responseText;
        } else {
          errorNotFound(srcpath);
        }
        if (callback) {
          callback(res);
        }
      }
    };
    xhr.open('GET', srcpathNoCache(srcpath), !!callback);
    xhr.send();
    return res;
  };
  xhrSyncScriptLoad = function(srcpath) {
    doc.head.appendChild(doc.createElement('script')).text = '//src:' + srcpath + getFile(srcpath);
  };
  (read = win['read'] = function(required, srcpath) {
    var cls;
    if (!(cls = checkPersence(required))) {
      if (srcpath && !required_obj[srcpath]) {
        required_obj[srcpath += '.js'] = true;
        xhrSyncScriptLoad(srcpath);
      } else {
        errorNotFound(required);
      }
    }
    if (!(cls = checkPersence(required))) {
      errorNotFound(required);
    }
    return cls;
  })['ns'] = function(keywords, swap) {
    var i, len, par, temp;
    keywords = keywords.split('.');
    i = 0;
    len = keywords.length;
    temp = win;
    while (i < len) {
      if (!temp[keywords[i]]) {
        break;
      }
      par = temp;
      temp = temp[keywords[i]];
      i++;
    }
    while (i < len) {
      par = temp;
      temp = temp[keywords[i]] = {};
      i++;
    }
    if (swap) {
      for (i in temp) {
        if (swap[i] === void 0) {
          swap[i] = temp[i];
        }
      }
      temp = par[keywords[len - 1]] = swap;
    }
    return temp;
  };
  read['run'] = function(path) {
    var checkReadLoop, loadLoop, loaded_paths, require_ary, unitefile;
    path = path + '.js';
    require_ary = [];
    loaded_paths = {};
    unitefile = '';
    checkReadLoop = function(jspath) {
      require_ary.unshift(jspath);
      if (!required_obj[jspath]) {
        required_obj[jspath] = 1;
        getFile(jspath, function(filevalue) {
          var result, temp;
          unitefile = filevalue + unitefile;
          if (result = unitefile.match(reg_readmethod)) {
            temp = result[1] + '.js';
            unitefile = unitefile.slice(result.index + result[0].length);
            require_ary.unshift(temp);
            return checkReadLoop(temp);
          }
          loadLoop();
        });
      }
    };
    loadLoop = function() {
      var loadaction, script, src;
      if (src = require_ary.shift()) {
        if (!loaded_paths[src]) {
          loaded_paths[src] = 1;
          script = doc.createElement('script');
          loadaction = function() {
            script.removeEventListener('load', loadaction);
            loadLoop();
          };
          script.addEventListener('load', loadaction);
          script.src = srcpathNoCache(src);
          doc.head.appendChild(script);
        } else {
          loadLoop();
        }
      }
    };
    checkReadLoop(path);
  };
})(window, document, {}, /[=,;:&\n\(\|]\s*read\(.+?,\s*['"](.+?)['"]\)/, (function(required) {
  throw Error('not found ' + required);
}), +(new Date));
